[theme]

# Primary accent for interactive elements
primaryColor = '#f64c72'

# Background color for the main content area
backgroundColor = '#2f2fa2'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#242582'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"